// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/import-parts" | "/admin/manage-backlog" | "/admin/roles" | "/admin/sql-query" | "/admin/sync-parts" | "/admin/users" | "/dashboard" | "/login" | "/process" | "/process/changes" | "/process/documents" | "/products" | "/products/changes" | "/products/documents" | "/users" | "/users/roles"
type AppRouteHandlerRoutes = "/api/admin/cc-users" | "/api/admin/engineer-roles" | "/api/admin/import-parts" | "/api/admin/job-notes" | "/api/admin/job-status" | "/api/admin/query-database" | "/api/admin/scan-parts" | "/api/admin/sync-parts" | "/api/auth/[...nextauth]" | "/api/dashboard/current-jobs" | "/api/dashboard/team-backlog" | "/api/health" | "/api/process" | "/api/process/[id]" | "/api/products" | "/api/products/[id]" | "/api/products/bom" | "/api/products/production" | "/api/products/where-used" | "/api/roles" | "/api/roles/[id]" | "/api/roles/[id]/users" | "/api/users" | "/api/users/[id]" | "/api/users/[id]/password" | "/api/users/[id]/roles" | "/api/users/test"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/import-parts": {}
  "/admin/manage-backlog": {}
  "/admin/roles": {}
  "/admin/sql-query": {}
  "/admin/sync-parts": {}
  "/admin/users": {}
  "/api/admin/cc-users": {}
  "/api/admin/engineer-roles": {}
  "/api/admin/import-parts": {}
  "/api/admin/job-notes": {}
  "/api/admin/job-status": {}
  "/api/admin/query-database": {}
  "/api/admin/scan-parts": {}
  "/api/admin/sync-parts": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/dashboard/current-jobs": {}
  "/api/dashboard/team-backlog": {}
  "/api/health": {}
  "/api/process": {}
  "/api/process/[id]": { "id": string; }
  "/api/products": {}
  "/api/products/[id]": { "id": string; }
  "/api/products/bom": {}
  "/api/products/production": {}
  "/api/products/where-used": {}
  "/api/roles": {}
  "/api/roles/[id]": { "id": string; }
  "/api/roles/[id]/users": { "id": string; }
  "/api/users": {}
  "/api/users/[id]": { "id": string; }
  "/api/users/[id]/password": { "id": string; }
  "/api/users/[id]/roles": { "id": string; }
  "/api/users/test": {}
  "/dashboard": {}
  "/login": {}
  "/process": {}
  "/process/changes": {}
  "/process/documents": {}
  "/products": {}
  "/products/changes": {}
  "/products/documents": {}
  "/users": {}
  "/users/roles": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
