// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/(dashboard)/admin/import-parts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/import-parts">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/admin/import-parts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/admin/manage-backlog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/manage-backlog">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/admin/manage-backlog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/admin/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/roles">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/admin/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/admin/sql-query/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sql-query">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/admin/sql-query/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/admin/sync-parts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sync-parts">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/admin/sync-parts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/process/changes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/process/changes">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/process/changes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/process/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/process/documents">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/process/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/process/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/process">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/process/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/products/changes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/changes">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/products/changes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/products/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/documents">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/products/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/users/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users/roles">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/users/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/cc-users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cc-users">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/cc-users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/engineer-roles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/engineer-roles">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/engineer-roles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/import-parts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/import-parts">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/import-parts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/job-notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/job-notes">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/job-notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/job-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/job-status">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/job-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/query-database/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/query-database">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/query-database/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/scan-parts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/scan-parts">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/scan-parts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/sync-parts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/sync-parts">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/sync-parts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/dashboard/current-jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/current-jobs">> = Specific
  const handler = {} as typeof import("../../../app/api/dashboard/current-jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/dashboard/team-backlog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/team-backlog">> = Specific
  const handler = {} as typeof import("../../../app/api/dashboard/team-backlog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/process/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/process/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/process/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/process/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/process">> = Specific
  const handler = {} as typeof import("../../../app/api/process/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/products/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/bom/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/bom">> = Specific
  const handler = {} as typeof import("../../../app/api/products/bom/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/production/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/production">> = Specific
  const handler = {} as typeof import("../../../app/api/products/production/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products">> = Specific
  const handler = {} as typeof import("../../../app/api/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/where-used/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/where-used">> = Specific
  const handler = {} as typeof import("../../../app/api/products/where-used/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/roles/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/roles/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/roles/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/roles/[id]/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/roles/[id]/users">> = Specific
  const handler = {} as typeof import("../../../app/api/roles/[id]/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/roles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/roles">> = Specific
  const handler = {} as typeof import("../../../app/api/roles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/users/[id]/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]/password">> = Specific
  const handler = {} as typeof import("../../../app/api/users/[id]/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/users/[id]/roles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]/roles">> = Specific
  const handler = {} as typeof import("../../../app/api/users/[id]/roles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../../app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/users/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/test">> = Specific
  const handler = {} as typeof import("../../../app/api/users/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
