/**
 * Daily Plan query (Paradigm / PDMLIV, read-only MSSQL).
 *
 * The original report used ~10 correlated subqueries evaluated per work-order
 * row (DATA0044/45 params, DATA0038 step lookups, DATA0003 holiday counts,
 * DATA0098 RMA, and a per-row SUM over vw_wo_layer_all). Per-row execution is
 * what made it run 2-3 minutes.
 *
 * This version is set-based: each source is touched once via a JOIN to a
 * pre-grouped derived table, so the optimizer can hash/merge-join instead of
 * re-seeking per row. No new DB objects are needed (account is read-only) — the
 * gain is purely from the rewrite. READ UNCOMMITTED is applied by queryMSSQL.
 *
 * REMAINING_LABOR_HOURS (the per-row SUM over vw_wo_layer_all — the single
 * biggest cost) is intentionally NOT in this query. It's fetched lazily by the
 * labor-hours endpoint only when the user asks for it.
 */
export const DAILY_PLAN_SQL = `
;WITH
-- Max step number per source (was a correlated MAX in CURRENT_STEP_OF_STEPS)
StepMax AS (
  SELECT SOURCE_PTR, MAX(STEP_NUMBER) AS MAX_STEP
  FROM DATA0038 WITH (NOLOCK)
  GROUP BY SOURCE_PTR
),
-- Percent-complete per (source, step) (was a correlated lookup)
StepPct AS (
  SELECT SOURCE_PTR, STEP_NUMBER, MIN(PERCENT_COMPLETE) AS PERCENT_COMPLETE
  FROM DATA0038 WITH (NOLOCK)
  WHERE TTYPE = '2'
  GROUP BY SOURCE_PTR, STEP_NUMBER
),
-- Product parameters, pivoted once per (source, type) instead of 3 subqueries
Param AS (
  SELECT SOURCE_PTR, SOURCE_TYPE,
         MAX(PROD_PARA_03) AS FLBDTK,
         MAX(PROD_PARA_04) AS CIRC_SIZE,
         MAX(PROD_PARA_08) AS PNL_SIZE
  FROM DATA0044 WITH (NOLOCK)
  GROUP BY SOURCE_PTR, SOURCE_TYPE
),
Spec AS (
  SELECT SOURCE_PTR, SOURCE_TYPE, MAX(PROD_SPEC_01) AS MATERIAL
  FROM DATA0045 WITH (NOLOCK)
  GROUP BY SOURCE_PTR, SOURCE_TYPE
),
-- Current step per work order, from the live production-transaction table
-- (DATA9469). A WO can be split across several active steps; we take the
-- EARLIEST active step (the "tail" — where work is still pending) as the current
-- step, and carry that step's entry date/time and work center. DATA9469 keys on
-- WORK_ORDER_NO (string) — collation-forced to survive the server's mixed
-- collations. A WO with no DATA9469 row simply hasn't started (blank is correct).
CurrentStep AS (
  SELECT x.WORK_ORDER_NO, x.STEP_NO, x.WORK_CENTER, x.WORK_CENTER_NAME,
         x.DATE_IN, x.TIME_IN, x.QUAN_IN_BKLG, x.SALES_ORDER
  FROM (
    SELECT WORK_ORDER_NO, STEP_NO, WORK_CENTER, WORK_CENTER_NAME, DATE_IN, TIME_IN, QUAN_IN_BKLG, SALES_ORDER,
           ROW_NUMBER() OVER (
             PARTITION BY WORK_ORDER_NO COLLATE DATABASE_DEFAULT
             ORDER BY STEP_NO ASC
           ) AS rn
    FROM DATA9469 WITH (NOLOCK)
  ) x
  WHERE x.rn = 1
)
SELECT DATA0010_1.ABBR_NAME
, DATA0050_1.CUSTOMER_PART_NUMBER
, CS.SALES_ORDER
, DATA0006_1.WORK_ORDER_NUMBER AS WORK_ORDER
, DATA0006_1.PRIORITY_CODE AS PTY
, CASE WHEN DATA0006_1.WORK_ORDER_NUMBER NOT LIKE '%-000' THEN DATA0017_1.INV_PART_NUMBER
  WHEN DATA0006_1.WORK_ORDER_NUMBER LIKE 'W%-000' THEN DATA0017_3.INV_PART_NUMBER
  WHEN DATA0006_1.WORK_ORDER_NUMBER LIKE '%-000' THEN DATA0017_2.INV_PART_NUMBER
  END AS INV_PART_NUMBER
, CASE WHEN DATA0006_1.WORK_ORDER_NUMBER NOT LIKE '%-000'  THEN DATA0017_1.INV_PART_DESCRIPTION
  WHEN DATA0006_1.WORK_ORDER_NUMBER LIKE 'W%-000' THEN DATA0017_3.INV_PART_NUMBER
  WHEN DATA0006_1.WORK_ORDER_NUMBER LIKE '%-000' THEN DATA0017_2.INV_PART_DESCRIPTION
  END AS INV_PART_DESCRIPTION
, SUBSTRING(CAST(DATA0006_1.QUAN_SCH AS CHAR),1,9) AS SCHED
, SUBSTRING(CAST(CS.QUAN_IN_BKLG AS CHAR ),1,9) AS BKLG
, SUBSTRING(CAST(CASE WHEN (DATA0006_1.PARTS_PER_PANEL = '0') THEN CS.QUAN_IN_BKLG
  WHEN (DATA0006_1.PARTS_PER_PANEL > '0') THEN (CS.QUAN_IN_BKLG/DATA0006_1.PARTS_PER_PANEL)
  END AS CHAR),1,4) AS PNLS
, SUBSTRING(CAST(DATA0006_1.PARTS_PER_PANEL AS CHAR),1,4) AS NRUP
, CS.STEP_NO AS STEP
, (CAST(CS.STEP_NO AS VARCHAR) + ' OF ' + CAST(StepMax.MAX_STEP AS VARCHAR)) AS CURRENT_STEP_OF_STEPS
, SUBSTRING((CASE DATA0006_1.PROD_STATUS WHEN '2' THEN '....UNRELEASED....'
  WHEN '206' THEN 'xxxON HOLD UNRELxxx'
  WHEN '306' THEN 'xxxON HOLD RELxxx'
  ELSE CS.WORK_CENTER_NAME
  END),1,20) AS LOCATION
, CASE WHEN DATA0006_1.WORK_ORDER_NUMBER NOT LIKE '%-000' THEN DATA0017_1.DISC_1
  WHEN DATA0006_1.WORK_ORDER_NUMBER LIKE '%-000' THEN DATA0050_1.FIXED_SCRAP_RATE
  END AS YEILD
, CS.DATE_IN
, DATA0006_1.SCH_COMPL_DATE AS SCH_COMP
, DATA0008_1.PROD_CODE AS PROD_CODE
, DATA0008_1.ANALYSIS_CODE5 AS PROD_LINE
, DATA0015_1.WAREHOUSE_CODE
, SUBSTRING(DATA0015_1.WAREHOUSE_NAME,1,6) AS NAME
, DATA0006_1.ANALYSIS_CODE_3 AS ANALYSIS_CODE_3
, DATA0006_1.ANALYSIS_CODE_5 AS ANALYSIS_CODE_5
, CASE WHEN DATA0006_1.WORK_ORDER_NUMBER NOT LIKE '%-000' THEN ParamInv.FLBDTK
  WHEN DATA0006_1.WORK_ORDER_NUMBER LIKE '%-000' THEN ParamCust.FLBDTK END AS FLBDTK
, CASE WHEN DATA0006_1.WORK_ORDER_NUMBER NOT LIKE '%-000' THEN ParamInv.CIRC_SIZE
  WHEN DATA0006_1.WORK_ORDER_NUMBER LIKE '%-000' THEN ParamCust.CIRC_SIZE END AS CIRC_SIZE
, CASE WHEN DATA0006_1.WORK_ORDER_NUMBER NOT LIKE '%-000' THEN ParamInv.PNL_SIZE
  WHEN DATA0006_1.WORK_ORDER_NUMBER LIKE '%-000' THEN ParamCust.PNL_SIZE END AS PNL_SIZE
, CASE WHEN DATA0006_1.WORK_ORDER_NUMBER NOT LIKE '%-000' THEN SpecInv.MATERIAL
  WHEN DATA0006_1.WORK_ORDER_NUMBER LIKE '%-000' THEN SpecCust.MATERIAL END AS MATERIAL
, CASE WHEN DATA0006_1.WORK_ORDER_NUMBER NOT LIKE '%-000' THEN DATA0017_1.PROD_LEAD_TIME
  WHEN DATA0006_1.WORK_ORDER_NUMBER LIKE '%-000' THEN DATA0050_1.MFG_LEAD_TIME
  END AS PROD_LEAD_TIME
, CASE WHEN DATA0006_1.WORK_ORDER_NUMBER NOT LIKE '%-000' THEN (DATA0006_1.SCH_COMPL_DATE - (DATA0017_1.PROD_LEAD_TIME + (2 * (DATA0017_1.PROD_LEAD_TIME/5))))
  ELSE (DATA0006_1.SCH_COMPL_DATE - (DATA0050_1.MFG_LEAD_TIME + (2 * (DATA0050_1.MFG_LEAD_TIME/5))))
  END AS CALC_START_DATE
, D98.RMA_NUMBER AS RMA_NUMBER
, CASE WHEN CS.DATE_IN IS NULL THEN 0
  ELSE CASE WHEN (DATEDIFF(DAY,CS.DATE_IN, GETDATE()) - (((DATEDIFF(WK, CS.DATE_IN, GETDATE()) * 2) + (CASE WHEN DATENAME(DW, CS.DATE_IN) = 'SUNDAY' THEN 1 ELSE 0 END)
    + (CASE WHEN DATENAME(DW, CS.DATE_IN) = 'SATURDAY' THEN 1 ELSE 0 END)) + ISNULL(Hol.HOL_COUNT,0))) > 0
    THEN (DATEDIFF(DAY,CS.DATE_IN, GETDATE()) - (((DATEDIFF(WK, CS.DATE_IN, GETDATE()) * 2) + (CASE WHEN DATENAME(DW, CS.DATE_IN) = 'SUNDAY' THEN 1 ELSE 0 END)
    + (CASE WHEN DATENAME(DW, CS.DATE_IN) = 'SATURDAY' THEN 1 ELSE 0 END)) + ISNULL(Hol.HOL_COUNT,0)))
    ELSE 1
  END
  END AS DAYS_IN
, StepPctSel.PERCENT_COMPLETE AS PERCENT_COMPLETE
, D34.DEPT_CODE
, D34.DEPT_NAME
, CS.WORK_CENTER AS STEP_DEPT_CODE
, CS.WORK_CENTER_NAME AS STEP_DEPT_NAME
-- Time at current step: entry date/time (from DATA9469) + calendar days since.
, CS.DATE_IN AS STEP_DATE_IN
, CS.TIME_IN AS STEP_TIME_IN
, CASE WHEN CS.DATE_IN IS NULL THEN NULL
       ELSE DATEDIFF(DAY, CS.DATE_IN, GETDATE()) END AS CAL_DAYS_AT_STEP
FROM DATA0006 AS DATA0006_1 WITH (NOLOCK)
LEFT OUTER JOIN DATA0050 AS DATA0050_1 WITH (NOLOCK) ON DATA0006_1.CUST_PART_PTR = DATA0050_1.RKEY
LEFT OUTER JOIN DATA0010 AS DATA0010_1 WITH (NOLOCK) ON DATA0050_1.CUSTOMER_PTR = DATA0010_1.RKEY
LEFT OUTER JOIN DATA0008 AS DATA0008_1 WITH (NOLOCK) ON DATA0050_1.PROD_CODE_PTR = DATA0008_1.RKEY
LEFT OUTER JOIN DATA0015 AS DATA0015_1 WITH (NOLOCK) ON DATA0015_1.RKEY = DATA0006_1.WHOUSE_PTR
LEFT OUTER JOIN DATA0017 AS DATA0017_1 WITH (NOLOCK) ON DATA0006_1.INVENTORY_PTR = DATA0017_1.RKEY
LEFT OUTER JOIN DATA0025 AS DATA0025_1 WITH (NOLOCK) ON DATA0025_1.RKEY = DATA0006_1.BOM_PTR
LEFT OUTER JOIN DATA0017 AS DATA0017_2 WITH (NOLOCK) ON DATA0017_2.RKEY = DATA0025_1.INVENTORY_PTR
LEFT OUTER JOIN DATA0025 AS DATA0025_2 WITH (NOLOCK) ON DATA0025_2.RKEY = DATA0050_1.BOM_PTR
LEFT OUTER JOIN DATA0017 AS DATA0017_3 WITH (NOLOCK) ON DATA0017_3.RKEY = DATA0025_2.INVENTORY_PTR
LEFT OUTER JOIN DATA0038 AS DATA0038_1 WITH (NOLOCK) ON DATA0038_1.SOURCE_PTR = DATA0006_1.RKEY AND CS.STEP_NO = DATA0038_1.STEP_NUMBER
LEFT OUTER JOIN DATA0034 AS D34 WITH (NOLOCK) ON DATA0038_1.DEPT_PTR = D34.RKEY
-- derived joins replacing the correlated subqueries --
LEFT OUTER JOIN CurrentStep AS CS             ON CS.WORK_ORDER_NO COLLATE DATABASE_DEFAULT = DATA0006_1.WORK_ORDER_NUMBER COLLATE DATABASE_DEFAULT
LEFT OUTER JOIN StepMax                       ON StepMax.SOURCE_PTR = DATA0006_1.RKEY
LEFT OUTER JOIN StepPct AS StepPctSel         ON StepPctSel.SOURCE_PTR = DATA0006_1.RKEY AND StepPctSel.STEP_NUMBER = CS.STEP_NO
LEFT OUTER JOIN Param   AS ParamInv           ON ParamInv.SOURCE_PTR = DATA0017_1.RKEY AND ParamInv.SOURCE_TYPE = '1'
LEFT OUTER JOIN Param   AS ParamCust          ON ParamCust.SOURCE_PTR = DATA0050_1.RKEY AND ParamCust.SOURCE_TYPE = '2'
LEFT OUTER JOIN Spec    AS SpecInv            ON SpecInv.SOURCE_PTR = DATA0017_1.RKEY AND SpecInv.SOURCE_TYPE = '1'
LEFT OUTER JOIN Spec    AS SpecCust           ON SpecCust.SOURCE_PTR = DATA0050_1.RKEY AND SpecCust.SOURCE_TYPE = '2'
LEFT OUTER JOIN DATA0098 AS D98 WITH (NOLOCK) ON D98.RKEY = DATA0006_1.RMA_PTR
OUTER APPLY (
  SELECT COUNT(*) AS HOL_COUNT
  FROM DATA0003 D3 WITH (NOLOCK)
  WHERE D3.TDATE BETWEEN CS.DATE_IN AND GETDATE()
) AS Hol
WHERE DATA0006_1.PROD_STATUS IN (2,3,206,306)
ORDER BY DATA0050_1.CUSTOMER_PART_NUMBER
`
